### ISSUE TITLE
Dependencies and optional dependencies (opencog)

### ISSUE THREAD

**Issue by Radivarig** [opencog/opencog-nix#4]
**Mandatory**:
  - [x] cmake
  - [x] cogutil
  - [x] atomspace
  - [x] link-grammar
  - [x] boost166
  - [x] guile
  - [x] gmp # dep of guile
  - [x] octomap
  - [x] libuuid
  - [x] python3
  - [x] python3Packages.cython

**Optional**:
  - [x] moses
  - [x] cxxtest
  - [x] pkgconfig
  - [x] pcre
  - [x] valgrind # debugging
  - [x] stack # maybe mandatory later
  - [x] doxygen # documentation

**Deprecated** (or soon to be):
  - [x] cpprest # soon [note](https://github.com/opencog/opencog/blob/ffdecc632e62dbf8ffb5a9f76278808c033de4f7/CMakeLists.txt#L208)
  - [x] gtk3
  - [x] blas
  - [x] liblaplack
  - [x] protobuf
  - [x] jsoncpp [note](https://github.com/opencog/opencog/blob/ffdecc632e62dbf8ffb5a9f76278808c033de4f7/CMakeLists.txt#L446)
  - [x] tbb [note](https://github.com/opencog/opencog/blob/ffdecc632e62dbf8ffb5a9f76278808c033de4f7/CMakeLists.txt#L446)
  - [x] zeromq [note](https://github.com/opencog/opencog/blob/ffdecc632e62dbf8ffb5a9f76278808c033de4f7/CMakeLists.txt#L446)

**Comment by linas** [comment]
This list needs fixes. Its both over-broad, and is missing several important pieces.

gmp, gtk3, graphviz xorg.pthreads definitely not wanted; undesired, it enables dead, obsolete code.

link-grammar is 100% mandatory.
octomap is not yet mandatory, but soon will be.

python3 instead of python2 very strongly urged.

blas and lapack really not needed/wanted except for an unused, mostly-obsolete component.

valgrgrind definitely not needed except for debugging

stack pretty much not needed except for experimental development.

jsoncpp, tbb, protobuff are used only in a broken, deprecated component, that needs a total overhaul or to be dumped. 

doxygen not needed unless building documentation for some website.

**Comment by linas** [comment]
You also titled this as "optional dependencies". But some are mandatory:
cmake, coguitl, atomspace, boost, guile, python3, cython3, link-grammar (I guess libuuid?) and octomap. 

stack might become mandatory, depending on status that I'm not tracking closely.

Everything else is unwanted, discouraged, stale, obsolete.

**Comment by Radivarig** [comment]
I followed the build output and thought to include the missing ones. Should I remove unwanted completely, or leave them commented?

What about `cpprest`? [This line](https://github.com/opencog/opencog/blob/ffdecc632e62dbf8ffb5a9f76278808c033de4f7/CMakeLists.txt#L208) says it will be removed when pattern miner is replaced with a new one. It builds, though it takes a bit, and would still need to patch `CMakeLists.txt` since it did not recognize the version.

What about `moses` that will be replaced with `as-moses`? I assume build both and leave one commented?

**Comment by Radivarig** [comment]
Same for `zeromq` by [this](https://github.com/opencog/opencog/blob/ffdecc632e62dbf8ffb5a9f76278808c033de4f7/CMakeLists.txt#L446) line

**Comment by linas** [comment]
The new pattern miner is complete -- and has been for a month or two, and the old pattern miner will be removed "any day now", whenever Nil thinks he's really really ready.  There might still be users of the old pattern miner. Not sure.

Re: the AtomSpacePublisherModule: there may be users of this. I don't want to pull the rug out from under them, just yet, because I don't have a replacement, nor is there a warm body available to create a replacement. But I also do not want to carry it forward, to new platforms. It needs to fade away.

moses is in use, but it is not a dependency of opencog.  moses depends on cogutil, and I thnk maybe?? it has guile bindings, which would make it depend on the atomspace. Not sure.

It will be years before as-moses is ready. it will defineitely depend on the atomspace, but not on opencog.

**Comment by Radivarig** [comment]
I've added the rest of the packages and commented out the deprecated ones
